language: node_js
node_js:
  - "6"
before_install:  
  - npm install -g npm
before_script:
  - npm install -g gulp
script:
  - gulp jasmine
after_script:
  -  cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
after_success: 'npm run coverage'