language: node_js
node_js:
  - "6"
before_install:  
  - npm install -g npm
before_script:
  - npm install -g gulp
script:
  - gulp jasmine
after_script:
  - node node_modules/lcov-filter/index.js lcov.info config | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

